# Generated by Django 4.0.1 on 2022-01-28 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0003_auto_20220126_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='story',
            name='f',
        ),
        migrations.AddField(
            model_name='story',
            name='f',
            field=models.ManyToManyField(related_name='false_story', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='story',
            name='t',
        ),
        migrations.AddField(
            model_name='story',
            name='t',
            field=models.ManyToManyField(related_name='true_story', to=settings.AUTH_USER_MODEL),
        ),
    ]
